### ISSUE TITLE
GLPI 10.x.x

### ISSUE THREAD

**Issue by prybak** [FutureProcessing/glpi-webhook#6]
Please verify plugin against current 10.0.0. beta release. If needed, please update plugin and release as new version (2.0).

**Comment by mrjd19811** [comment]
Would like to see this, anything I can do to help? Just upgraded to RC1.

**Comment by mrjd19811** [comment]
So played around some, removed the upper limit from the version, and got it installed, attempted to configure and php-error show'd that the GLPI_ROOT Const was causing it to fail, so I changed it to /var/www/html on my installation and that allowed the config page to load.

But that's as far as I got so far. I get permission denied when I try to go direct to front/subscriptions.php, and I don't see any menu altering that added the "plugins->subscriptions" as the readme states.

**Comment by mikron-ia** [comment]
This is very much in progress. Currently the update is undergoing internal tests and once it passes should be available (either as a separate branch or as part of the `master` branch, depending on existence of issues) within days.

**Comment by mikron-ia** [comment]
@mrjd19811 - the changes that adjust the plugin to 10.0.x are on the [changes-for-2.0.0](https://github.com/FutureProcessing/glpi-webhook/tree/changes-for-2.0.0) branch. Feel free to test them, any feedback would be most welcome - feel free to create issues should you find any.

**Comment by acremonezi** [comment]
> @mrjd19811 - the changes that adjust the plugin to 10.0.x are on the [changes-for-2.0.0](https://github.com/FutureProcessing/glpi-webhook/tree/changes-for-2.0.0) branch. Feel free to test them, any feedback would be most welcome - feel free to create issues should you find any.

Just instaled and tested it. 
The result is that It is working perfectly. 
Congratulations!

**Comment by gljones2001** [comment]
@prybak How did you get MS Teams to work? I can't figure it out, I've tried editing the JS files, could you send me a copy of the ones you edited for this plugin?

**Comment by mikron-ia** [comment]
[Release 2.0.0](https://github.com/FutureProcessing/glpi-webhook/releases/tag/2.0.0) closes this issue. The other question raised in this thread (MS Teams) are concern of #10.
